# Generated by Django 3.2 on 2022-11-10 11:15
'''
# 배포 단계에서 확인해보고 수정 진행할 예정입니다.
#
'''
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('dir', models.TextField(blank=True)),
                ('key', models.TextField()),
            ],
        ),
    ]
